// -----------------------------------------------------------------------
// Same test as tb_xsim_top_sps16_default.sv (no AXI4-Lite write, sps_sel
// stays at its reset default = SPS16 -- sidesteps the unrelated sps_sel
// write race, see README/Note.md), but re-targeted at the current DUT
// interface after two src/top.cpp changes:
//   1. HW_DEBUG_MODE disabled -- debug_current_bit/debug_alpha/debug_pulse/
//      debug_phase/debug_freq ports no longer exist on tfm_modulator, so
//      all connections to them are removed here (compile would fail
//      against the current hls_prj/solution1/syn/verilog/*.v otherwise).
//   2. cold_start applied to src/top.cpp itself (see Note.md) -- this run
//      is the RTL-vs-golden check for that change.
//   3. COS_LUT/SIN_LUT/cos_val/sin_val switched from data_t (Q4.12) to
//      dac_q15_t (Q1.15, ap_fixed<16,1,AP_RND,AP_SAT>) to match
//      tx_adrv9009_tpl_core's DAC sample format (see Note.md) -- the
//      i_val/q_val reconstruction below divides by 2^15, not 2^12.
// Golden reference: hls_prj/solution1/csim/build/output_waveform.csv,
// freshly regenerated by the same src/top.cpp (with cold_start + Q1.15
// output) via csim_design, SPS=16 (tb_top.cpp's default TEST_SPS_SEL=0).
// -----------------------------------------------------------------------
`timescale 1ns/1ps

module tb_xsim_top_sps16_default_coldstart;

    localparam CLK_PERIOD = 6.25;
    localparam integer NUM_BYTES = 8;
    localparam integer SPS = 16;             // sps_sel stays at its reset default (0) -> SPS=16
    localparam integer RUN_CYCLES = 1400;    // NUM_BYTES*SPS*8 = 1024 samples + pipeline fill + margin

    reg ap_clk = 0;
    reg ap_rst_n = 0;

    reg  [7:0] bit_in_TDATA  = 8'h00;
    reg        bit_in_TVALID = 1'b0;
    wire       bit_in_TREADY;
    reg  [0:0] bit_in_TKEEP  = 1'b1;
    reg  [0:0] bit_in_TSTRB  = 1'b1;
    reg  [0:0] bit_in_TLAST  = 1'b0;

    wire [15:0] i_out_TDATA;
    wire        i_out_TVALID;
    reg         i_out_TREADY = 1'b1;
    wire [1:0]  i_out_TKEEP;
    wire [1:0]  i_out_TSTRB;
    wire [0:0]  i_out_TLAST;

    wire [15:0] q_out_TDATA;
    wire        q_out_TVALID;
    reg         q_out_TREADY = 1'b1;
    wire [1:0]  q_out_TKEEP;
    wire [1:0]  q_out_TSTRB;
    wire [0:0]  q_out_TLAST;

    // s_axi_CTRL left completely idle -- no write, sps_sel stays at reset default.
    reg         s_axi_CTRL_AWVALID = 1'b0;
    wire        s_axi_CTRL_AWREADY;
    reg  [4:0]  s_axi_CTRL_AWADDR  = 5'h0;
    reg         s_axi_CTRL_WVALID  = 1'b0;
    wire        s_axi_CTRL_WREADY;
    reg  [31:0] s_axi_CTRL_WDATA   = 32'h0;
    reg  [3:0]  s_axi_CTRL_WSTRB   = 4'h0;
    reg         s_axi_CTRL_ARVALID = 1'b0;
    wire        s_axi_CTRL_ARREADY;
    reg  [4:0]  s_axi_CTRL_ARADDR  = 5'h0;
    wire        s_axi_CTRL_RVALID;
    reg         s_axi_CTRL_RREADY  = 1'b0;
    wire [31:0] s_axi_CTRL_RDATA;
    wire [1:0]  s_axi_CTRL_RRESP;
    wire        s_axi_CTRL_BVALID;
    reg         s_axi_CTRL_BREADY  = 1'b0;
    wire [1:0]  s_axi_CTRL_BRESP;

    tfm_modulator dut (
        .ap_clk(ap_clk),
        .ap_rst_n(ap_rst_n),
        .bit_in_TDATA(bit_in_TDATA),
        .bit_in_TVALID(bit_in_TVALID),
        .bit_in_TREADY(bit_in_TREADY),
        .bit_in_TKEEP(bit_in_TKEEP),
        .bit_in_TSTRB(bit_in_TSTRB),
        .bit_in_TLAST(bit_in_TLAST),
        .i_out_TDATA(i_out_TDATA),
        .i_out_TVALID(i_out_TVALID),
        .i_out_TREADY(i_out_TREADY),
        .i_out_TKEEP(i_out_TKEEP),
        .i_out_TSTRB(i_out_TSTRB),
        .i_out_TLAST(i_out_TLAST),
        .q_out_TDATA(q_out_TDATA),
        .q_out_TVALID(q_out_TVALID),
        .q_out_TREADY(q_out_TREADY),
        .q_out_TKEEP(q_out_TKEEP),
        .q_out_TSTRB(q_out_TSTRB),
        .q_out_TLAST(q_out_TLAST),
        .s_axi_CTRL_AWVALID(s_axi_CTRL_AWVALID),
        .s_axi_CTRL_AWREADY(s_axi_CTRL_AWREADY),
        .s_axi_CTRL_AWADDR(s_axi_CTRL_AWADDR),
        .s_axi_CTRL_WVALID(s_axi_CTRL_WVALID),
        .s_axi_CTRL_WREADY(s_axi_CTRL_WREADY),
        .s_axi_CTRL_WDATA(s_axi_CTRL_WDATA),
        .s_axi_CTRL_WSTRB(s_axi_CTRL_WSTRB),
        .s_axi_CTRL_ARVALID(s_axi_CTRL_ARVALID),
        .s_axi_CTRL_ARREADY(s_axi_CTRL_ARREADY),
        .s_axi_CTRL_ARADDR(s_axi_CTRL_ARADDR),
        .s_axi_CTRL_RVALID(s_axi_CTRL_RVALID),
        .s_axi_CTRL_RREADY(s_axi_CTRL_RREADY),
        .s_axi_CTRL_RDATA(s_axi_CTRL_RDATA),
        .s_axi_CTRL_RRESP(s_axi_CTRL_RRESP),
        .s_axi_CTRL_BVALID(s_axi_CTRL_BVALID),
        .s_axi_CTRL_BREADY(s_axi_CTRL_BREADY),
        .s_axi_CTRL_BRESP(s_axi_CTRL_BRESP)
    );

    always #(CLK_PERIOD/2.0) ap_clk = ~ap_clk;

    // Deassert TVALID in the same simulation step the handshake is detected
    // (not one extra clock edge later) -- see Note.md: an extra held-high
    // TVALID cycle risked a second, unintended TVALID&&TREADY beat (sending
    // the same byte twice) if regslice_both holds TREADY high for 2+ cycles.
    task automatic stream_byte(input [7:0] data, input is_last);
        begin
            @(posedge ap_clk);
            bit_in_TDATA  <= data;
            bit_in_TLAST  <= is_last;
            bit_in_TVALID <= 1'b1;
            while (!(bit_in_TVALID && bit_in_TREADY)) @(posedge ap_clk);
            bit_in_TVALID <= 1'b0;
        end
    endtask

    integer csv_file;
    integer sample_idx;
    real i_val, q_val;

    initial begin
        csv_file = $fopen("output_waveform_xsim_sps16_coldstart.csv", "w");
        $fwrite(csv_file, "Sample,I_Data,Q_Data,TLAST\n");
        sample_idx = 0;
    end

    always @(posedge ap_clk) begin
        if (ap_rst_n && i_out_TVALID && q_out_TVALID) begin
            // dac_q15_t (Q1.15): divide by 2^15, not 2^12 (data_t/Q4.12) -- see Note.md
            i_val = $signed(i_out_TDATA) / 32768.0;
            q_val = $signed(q_out_TDATA) / 32768.0;
            $fwrite(csv_file, "%0d,%f,%f,%0d\n", sample_idx, i_val, q_val, i_out_TLAST);
            sample_idx = sample_idx + 1;
        end
    end

    reg [7:0] test_data [0:NUM_BYTES-1];
    integer k;

    initial begin
        test_data[0] = 8'h67;
        test_data[1] = 8'h72;
        test_data[2] = 8'h74;
        test_data[3] = 8'hDE;
        test_data[4] = 8'h67;
        test_data[5] = 8'h72;
        test_data[6] = 8'h74;
        test_data[7] = 8'hDE;

        // All 8 bytes (including byte0) go through the exact same post-reset
        // stream_byte() handshake path -- see Note.md: pre-loading byte0
        // through reset doesn't skip the regslice_both settle-after-release
        // requirement anyway (confirmed both stimulus styles hit the same
        // idle-misfire pre-cold_start), so this is simply the simpler and
        // more realistic stimulus, matching the validated tb_xsim_verify_sps8_lut.sv.
        ap_rst_n = 1'b0;
        repeat (10) @(posedge ap_clk);
        ap_rst_n = 1'b1;

        for (k = 0; k < NUM_BYTES; k = k + 1) begin
            stream_byte(test_data[k], (k == NUM_BYTES-1));
        end

        repeat (RUN_CYCLES) @(posedge ap_clk);

        $fclose(csv_file);
        $display(">> XSIM (SPS=16 default, no AXI write, cold_start) finished. %0d samples captured.", sample_idx);
        $finish;
    end

endmodule
